---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBkNKz+MF4TsfUj/TLZJj1raFf2AX0tsNf9F622Sth4uyi4hTBRon+6bGv0rs9jD0tATiAZ7A+oshSERwHIYlBfOoUs7xmlqRqJ/QXJIAMK5ZHbfCPEN7+lpI9a/VpdV4ENYuU3DMxAYbn0GClZ1u5CpCfugVxFfTyhtEX78cANFHSX8jvhdw8uU9nNICIECHsCePj1JNN0MA8EJZd362E5p1UUgVBUTy8fVhJ7wC7pyr9csVtR6PNReVHNRHwc2fvRtk8xkFMhZitIzL1Kh5sPdNIxjMwjo4pRVM2W2bbqY+SsYcg5tEohwduA7S91pAHCGHC/i7eMARCg0hU2pIdd2idFQt0t7VKQy7oIW4OJTdEveD/8+iT65GonpyuOt8a2A5sAE5QHxfOfo4bZoTng8XnUh7ktXAn2PFMDAKs/sPLc5152Hml1HQhl+7uGX6+TNOynxz6ihYbU4/LCmFF4w7kUU31BWR57Nd+E5+wp+cwEHXLjLFkUywk5YS6quayCFVCskwln/8B/lGrtcVYyB9o/UgJDEZqjEk3sQHDiFQ2ojsLr8mDxkXD6SZxBlbVkXniy4OmLZRMnoe+84YXOQasmVBrQ65hbaUf7lzSLF+ZsnqnBps51er3tn+uk8M+fJs/FgsKWUeeNXvqa0m2ufbtoOxly5F8sfQdCZMjc02hrJRN+SSdNz/7AHAhAxMOJ19mhLj/mWLeyiEB3RWCGilE4SUccRNtGkg2VuPNjeRS1qF2ANRlgn26ipWZBRsfg7Q==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
